---
name: DateTimeX-Easy
version: 0.080
author:
  - 'Robert Krimen, C<< <rkrimen at cpan.org> >>'
abstract: Parse a date/time string using the best method available
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0
  DateTime::Format::DateParse: 0
  DateTime::Format::Flexible: 0
  DateTime::Format::Natural: 0
  Scalar::Util: 0
build_requires:
  Test::More: 0
recommends:
  DateTime::Format::DateManip: 0
  DateTime::Format::ICal: 0
provides:
  DateTimeX::Easy:
    file: lib/DateTimeX/Easy.pm
    version: 0.080
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
