---
abstract: 'Parse a date/time string using the best method available'
author:
  - 'Robert Krimen, C<< <rkrimen at cpan.org> >>'
build_requires:
  Test::Most: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTimeX-Easy
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  DateTime::Format::DateManip: 0
  DateTime::Format::DateParse: 0
  DateTime::Format::Flexible: 0
  DateTime::Format::ICal: 0
  DateTime::Format::Natural: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/datetimex-easy/tree/master
version: 0.086
